#!/usr/bin/env python

import os
import subprocess

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
SKIP_FOLDERS = [
    "./Modules",
    "./out",
    # './Template',
]


def get_tex_files():
    tex_files = []
    for root, dirs, files in os.walk("."):
        if root in SKIP_FOLDERS:
            continue

        for file in files:
            if file.endswith(".tex"):
                tex_files.append(os.path.join(root, file))
    return tex_files


def generate_tex():
    tex_files = get_tex_files()
    for tex_file in tex_files:
        subprocess.run(["latexmk", "-pdflua", "-cd", tex_file])


def collect_pdfs():
    pdfs = []
    for root, dirs, files in os.walk("."):
        if root in SKIP_FOLDERS:
            continue

        for file in files:
            if file.endswith(".pdf"):
                pdfs.append(os.path.join(root, file))
    return pdfs


generate_tex()
pdfs = collect_pdfs()

for pdf in pdfs:
    print(pdf)
